repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^backend/requirements\.txt$|^docs/
        stages: [pre-commit]
    -   id: end-of-file-fixer
        exclude: ^backend/requirements\.txt$|^docs/
        stages: [pre-commit]
    -   id: check-yaml
        stages: [pre-commit]
    -   id: check-added-large-files
        stages: [pre-commit]

-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black
        stages: [pre-commit]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss] # Removed markdown
        stages: [pre-commit]
        files: ^frontend/src/.*\.(js|jsx|ts|tsx|json|css|scss)$ # Removed md
