services:
  # Combined backend and frontend service
  - type: web
    name: terminus
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: '["https://terminus-aw4s.onrender.com", "*"]'
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: terminus-db
          property: connectionString
    healthCheckPath: /api/health

databases:
  - name: terminus-db
    plan: free
    databaseName: terminus_db
    user: postgres 