"""update_code_submission_status

Revision ID: 43b88c385fa2
Revises: f575de2cb419
Create Date: 2025-07-25 19:17:18.277685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b88c385fa2'
down_revision: Union[str, None] = 'f575de2cb419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_submissions', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_submissions', sa.Column('file_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
