"""rename_user_id_to_submitter_id

Revision ID: a5247ead5376
Revises: 43b88c385fa2
Create Date: 2025-07-25 19:18:09.124052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5247ead5376'
down_revision: Union[str, None] = '43b88c385fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_submissions', sa.Column('submitter_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'code_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'code_submissions', 'users', ['submitter_id'], ['id'])
    op.create_foreign_key(None, 'code_submissions', 'code_files', ['file_id'], ['id'])
    op.drop_column('code_submissions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_submissions', sa.Column('user_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'code_submissions', type_='foreignkey')
    op.drop_constraint(None, 'code_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'code_submissions', 'users', ['user_id'], ['id'])
    op.drop_column('code_submissions', 'submitter_id')
    # ### end Alembic commands ###
