"""add_file_id_to_code_submission

Revision ID: f575de2cb419
Revises: 358f8f05f758
Create Date: 2025-07-25 18:43:17.044385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f575de2cb419'
down_revision: Union[str, None] = '358f8f05f758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_submissions', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'code_submissions', 'code_files', ['file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'code_submissions', type_='foreignkey')
    op.drop_column('code_submissions', 'file_id')
    # ### end Alembic commands ###
